version: '3'
services:
  db:
    image: mariadb:latest
    volumes:
      - ./db/var/lib/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "dev"
      MYSQL_USER: "dev"
      MYSQL_PASSWORD: "dev"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=dev
      - PMA_PASSWORD=dev
    ports:
      - "4000:80"
    volumes:
      - ./db/phpmyadmin/sessions:/sessions
volumes:
  db: